DROP TABLE MILLION_ROWS_TABLE PURGE;
CREATE TABLE MILLION_ROWS_TABLE 
(
  COLUMN1 VARCHAR2(20) 
);

INSERT INTO MILLION_ROWS_TABLE(COLUMN1)
  SELECT dbms_random.string('X', 20)
    FROM 
      (SELECT ROWNUM FROM ALL_CATALOG WHERE ROWNUM <= 1000),
      (SELECT ROWNUM FROM all_catalog WHERE ROWNUM <= 1000);
COMMIT;

ALTER SYSTEM FLUSH BUFFER_CACHE;
